[program:schedulr-youtube]
process_name=%(program_name)s_%(process_num)02d
command=php{{PHP_VERSION}} {{APP_DIR}}/artisan queue:work --queue=youtube --max-jobs=1
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
user=www-data
numprocs=1
redirect_stderr=true
stdout_logfile={{APP_DIR}}/storage/logs/worker-youtube.log
stopwaitsecs=3600
