[program:schedulr-scheduler]
process_name=%(program_name)s_%(process_num)02d
command=php{{PHP_VERSION}} {{APP_DIR}}/artisan schedule:work
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
user=www-data
numprocs=1
redirect_stderr=true
stdout_logfile={{APP_DIR}}/storage/logs/scheduler.log
stopwaitsecs=3600
